### ISSUE TITLE
Traceback (most recent call last):   File "E:/becatPython/main.py", line 11, in <module>     from bottle.middleware import SessionMiddleware ModuleNotFoundError: No module named 'bottle.middleware'; 'bottle' is not a package

### ISSUE THREAD

**Issue by wenchangming211** [wenjunzhangp/becatPython#2]
哈喽，这个里面没那个模块呢
Traceback (most recent call last):
  File "E:/becatPython/main.py", line 11, in <module>
    from bottle.middleware import SessionMiddleware
ModuleNotFoundError: No module named 'bottle.middleware'; 'bottle' is not a package

**Comment by wenjunzhangp** [comment]
应该是上面的包没导入进来，所以会提示这个，看看缺失什么依赖包了吗
